name: revving_up
description: A Flutter app to emulate engine sounds based on CAN bus RPM data.

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers:
  provider:
  flutter_background:
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sounds/v12_f1_engine.mp3
    - assets/sounds/v8_engine.mp3
    # Add other sound files
