name: revving_up
description: A Flutter app to emulate engine sounds based on CAN bus RPM data.

publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: any
  flutter_background: any
  #audioplayers: ^6.1.0
  just_audio: ^0.9.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sounds/v8_mustang/
    # Add other sound files
