name: revving_up
description: A Flutter app to emulate engine sounds based on CAN bus RPM data.

publish_to: 'none'

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  provider: ^6.1.2
  flutter_background: ^1.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/sounds/v12_f1_engine.mp3
    - assets/sounds/v8_engine.mp3
    # Add other sound files
